services:
  postgres-master:
    image: docker.io/bitnami/postgresql:latest
    container_name: master_nego_db
    ports:
      - "5540:5432"
    restart: always
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: replication_user
      POSTGRESQL_REPLICATION_PASSWORD: replication_password
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: nego_db
      POSTGRESQL_PGAUDIT_LOG: READ,WRITE
      POSTGRESQL_LOG_HOSTNAME: "true"
    volumes:
      - postgres-master-db-volume:/bitnami/postgresql
    networks:
      - network_db

  postgres-replica1:
    image: docker.io/bitnami/postgresql:latest
    container_name: replica_nego_db
    depends_on:
      - postgres-master
    ports:
      - "5541:5432"
    restart: always
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: replication_user
      POSTGRESQL_REPLICATION_PASSWORD: replication_password
      POSTGRESQL_MASTER_HOST: postgres-master
      POSTGRESQL_MASTER_PORT_NUMBER: 5432  # Internal port, not the mapped port!
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres  # Needed for slave too
    volumes:
      - postgres-replica1-db-volume:/bitnami/postgresql
    networks:
      - network_db

  redis:
    image: redis:8.4.0
    container_name: redis_db
    restart: always
    command: redis-server --appendonly yes --requirepass cmjpqcqbc000104kzca2o86rw
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - network_db

  minio:
    image: minio/minio:latest
    container_name: minio_db
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: WqYNmSnOBT
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - network_db

networks:
  network_db:
    driver: bridge

volumes:
  minio_data:
  postgres-master-db-volume:
  postgres-replica1-db-volume:
  redis-data: