// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newAuction(db *gorm.DB, opts ...gen.DOOption) auction {
	_auction := auction{}

	_auction.auctionDo.UseDB(db, opts...)
	_auction.auctionDo.UseModel(&model.Auction{})

	tableName := _auction.auctionDo.TableName()
	_auction.ALL = field.NewAsterisk(tableName)
	_auction.AuctionID = field.NewString(tableName, "auction_id")
	_auction.ProductID = field.NewString(tableName, "product_id")
	_auction.StartingPrice = field.NewFloat64(tableName, "starting_price")
	_auction.ReservePrice = field.NewFloat64(tableName, "reserve_price")
	_auction.BidIncrement = field.NewFloat64(tableName, "bid_increment")
	_auction.CurrentPrice = field.NewFloat64(tableName, "current_price")
	_auction.StartTime = field.NewTime(tableName, "start_time")
	_auction.EndTime = field.NewTime(tableName, "end_time")
	_auction.AutoExtendMinutes = field.NewInt32(tableName, "auto_extend_minutes")
	_auction.Status = field.NewString(tableName, "status")
	_auction.WinningBidID = field.NewString(tableName, "winning_bid_id")
	_auction.WinningBidderID = field.NewString(tableName, "winning_bidder_id")
	_auction.FinalPrice = field.NewFloat64(tableName, "final_price")
	_auction.CreatedAt = field.NewTime(tableName, "created_at")
	_auction.UpdatedAt = field.NewTime(tableName, "updated_at")
	_auction.DeletedAt = field.NewField(tableName, "deleted_at")

	_auction.fillFieldMap()

	return _auction
}

type auction struct {
	auctionDo auctionDo

	ALL               field.Asterisk
	AuctionID         field.String
	ProductID         field.String
	StartingPrice     field.Float64
	ReservePrice      field.Float64
	BidIncrement      field.Float64
	CurrentPrice      field.Float64
	StartTime         field.Time
	EndTime           field.Time
	AutoExtendMinutes field.Int32
	Status            field.String
	WinningBidID      field.String
	WinningBidderID   field.String
	FinalPrice        field.Float64
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field

	fieldMap map[string]field.Expr
}

func (a auction) Table(newTableName string) *auction {
	a.auctionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a auction) As(alias string) *auction {
	a.auctionDo.DO = *(a.auctionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *auction) updateTableName(table string) *auction {
	a.ALL = field.NewAsterisk(table)
	a.AuctionID = field.NewString(table, "auction_id")
	a.ProductID = field.NewString(table, "product_id")
	a.StartingPrice = field.NewFloat64(table, "starting_price")
	a.ReservePrice = field.NewFloat64(table, "reserve_price")
	a.BidIncrement = field.NewFloat64(table, "bid_increment")
	a.CurrentPrice = field.NewFloat64(table, "current_price")
	a.StartTime = field.NewTime(table, "start_time")
	a.EndTime = field.NewTime(table, "end_time")
	a.AutoExtendMinutes = field.NewInt32(table, "auto_extend_minutes")
	a.Status = field.NewString(table, "status")
	a.WinningBidID = field.NewString(table, "winning_bid_id")
	a.WinningBidderID = field.NewString(table, "winning_bidder_id")
	a.FinalPrice = field.NewFloat64(table, "final_price")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *auction) WithContext(ctx context.Context) *auctionDo { return a.auctionDo.WithContext(ctx) }

func (a auction) TableName() string { return a.auctionDo.TableName() }

func (a auction) Alias() string { return a.auctionDo.Alias() }

func (a auction) Columns(cols ...field.Expr) gen.Columns { return a.auctionDo.Columns(cols...) }

func (a *auction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *auction) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 16)
	a.fieldMap["auction_id"] = a.AuctionID
	a.fieldMap["product_id"] = a.ProductID
	a.fieldMap["starting_price"] = a.StartingPrice
	a.fieldMap["reserve_price"] = a.ReservePrice
	a.fieldMap["bid_increment"] = a.BidIncrement
	a.fieldMap["current_price"] = a.CurrentPrice
	a.fieldMap["start_time"] = a.StartTime
	a.fieldMap["end_time"] = a.EndTime
	a.fieldMap["auto_extend_minutes"] = a.AutoExtendMinutes
	a.fieldMap["status"] = a.Status
	a.fieldMap["winning_bid_id"] = a.WinningBidID
	a.fieldMap["winning_bidder_id"] = a.WinningBidderID
	a.fieldMap["final_price"] = a.FinalPrice
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a auction) clone(db *gorm.DB) auction {
	a.auctionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a auction) replaceDB(db *gorm.DB) auction {
	a.auctionDo.ReplaceDB(db)
	return a
}

type auctionDo struct{ gen.DO }

func (a auctionDo) Debug() *auctionDo {
	return a.withDO(a.DO.Debug())
}

func (a auctionDo) WithContext(ctx context.Context) *auctionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a auctionDo) ReadDB() *auctionDo {
	return a.Clauses(dbresolver.Read)
}

func (a auctionDo) WriteDB() *auctionDo {
	return a.Clauses(dbresolver.Write)
}

func (a auctionDo) Session(config *gorm.Session) *auctionDo {
	return a.withDO(a.DO.Session(config))
}

func (a auctionDo) Clauses(conds ...clause.Expression) *auctionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a auctionDo) Returning(value interface{}, columns ...string) *auctionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a auctionDo) Not(conds ...gen.Condition) *auctionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a auctionDo) Or(conds ...gen.Condition) *auctionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a auctionDo) Select(conds ...field.Expr) *auctionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a auctionDo) Where(conds ...gen.Condition) *auctionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a auctionDo) Order(conds ...field.Expr) *auctionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a auctionDo) Distinct(cols ...field.Expr) *auctionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a auctionDo) Omit(cols ...field.Expr) *auctionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a auctionDo) Join(table schema.Tabler, on ...field.Expr) *auctionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a auctionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *auctionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a auctionDo) RightJoin(table schema.Tabler, on ...field.Expr) *auctionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a auctionDo) Group(cols ...field.Expr) *auctionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a auctionDo) Having(conds ...gen.Condition) *auctionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a auctionDo) Limit(limit int) *auctionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a auctionDo) Offset(offset int) *auctionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a auctionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *auctionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a auctionDo) Unscoped() *auctionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a auctionDo) Create(values ...*model.Auction) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a auctionDo) CreateInBatches(values []*model.Auction, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a auctionDo) Save(values ...*model.Auction) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a auctionDo) First() (*model.Auction, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Auction), nil
	}
}

func (a auctionDo) Take() (*model.Auction, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Auction), nil
	}
}

func (a auctionDo) Last() (*model.Auction, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Auction), nil
	}
}

func (a auctionDo) Find() ([]*model.Auction, error) {
	result, err := a.DO.Find()
	return result.([]*model.Auction), err
}

func (a auctionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Auction, err error) {
	buf := make([]*model.Auction, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a auctionDo) FindInBatches(result *[]*model.Auction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a auctionDo) Attrs(attrs ...field.AssignExpr) *auctionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a auctionDo) Assign(attrs ...field.AssignExpr) *auctionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a auctionDo) Joins(fields ...field.RelationField) *auctionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a auctionDo) Preload(fields ...field.RelationField) *auctionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a auctionDo) FirstOrInit() (*model.Auction, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Auction), nil
	}
}

func (a auctionDo) FirstOrCreate() (*model.Auction, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Auction), nil
	}
}

func (a auctionDo) FindByPage(offset int, limit int) (result []*model.Auction, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a auctionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a auctionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a auctionDo) Delete(models ...*model.Auction) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *auctionDo) withDO(do gen.Dao) *auctionDo {
	a.DO = *do.(*gen.DO)
	return a
}
