// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newBid(db *gorm.DB, opts ...gen.DOOption) bid {
	_bid := bid{}

	_bid.bidDo.UseDB(db, opts...)
	_bid.bidDo.UseModel(&model.Bid{})

	tableName := _bid.bidDo.TableName()
	_bid.ALL = field.NewAsterisk(tableName)
	_bid.BidID = field.NewString(tableName, "bid_id")
	_bid.AuctionID = field.NewString(tableName, "auction_id")
	_bid.BidderID = field.NewString(tableName, "bidder_id")
	_bid.BidAmount = field.NewFloat64(tableName, "bid_amount")
	_bid.MaxBidAmount = field.NewFloat64(tableName, "max_bid_amount")
	_bid.BidStatus = field.NewString(tableName, "bid_status")
	_bid.IPAddress = field.NewString(tableName, "ip_address")
	_bid.UserAgent = field.NewString(tableName, "user_agent")
	_bid.CreatedAt = field.NewTime(tableName, "created_at")

	_bid.fillFieldMap()

	return _bid
}

type bid struct {
	bidDo bidDo

	ALL          field.Asterisk
	BidID        field.String
	AuctionID    field.String
	BidderID     field.String
	BidAmount    field.Float64
	MaxBidAmount field.Float64
	BidStatus    field.String
	IPAddress    field.String
	UserAgent    field.String
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (b bid) Table(newTableName string) *bid {
	b.bidDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bid) As(alias string) *bid {
	b.bidDo.DO = *(b.bidDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bid) updateTableName(table string) *bid {
	b.ALL = field.NewAsterisk(table)
	b.BidID = field.NewString(table, "bid_id")
	b.AuctionID = field.NewString(table, "auction_id")
	b.BidderID = field.NewString(table, "bidder_id")
	b.BidAmount = field.NewFloat64(table, "bid_amount")
	b.MaxBidAmount = field.NewFloat64(table, "max_bid_amount")
	b.BidStatus = field.NewString(table, "bid_status")
	b.IPAddress = field.NewString(table, "ip_address")
	b.UserAgent = field.NewString(table, "user_agent")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *bid) WithContext(ctx context.Context) *bidDo { return b.bidDo.WithContext(ctx) }

func (b bid) TableName() string { return b.bidDo.TableName() }

func (b bid) Alias() string { return b.bidDo.Alias() }

func (b bid) Columns(cols ...field.Expr) gen.Columns { return b.bidDo.Columns(cols...) }

func (b *bid) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bid) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 9)
	b.fieldMap["bid_id"] = b.BidID
	b.fieldMap["auction_id"] = b.AuctionID
	b.fieldMap["bidder_id"] = b.BidderID
	b.fieldMap["bid_amount"] = b.BidAmount
	b.fieldMap["max_bid_amount"] = b.MaxBidAmount
	b.fieldMap["bid_status"] = b.BidStatus
	b.fieldMap["ip_address"] = b.IPAddress
	b.fieldMap["user_agent"] = b.UserAgent
	b.fieldMap["created_at"] = b.CreatedAt
}

func (b bid) clone(db *gorm.DB) bid {
	b.bidDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bid) replaceDB(db *gorm.DB) bid {
	b.bidDo.ReplaceDB(db)
	return b
}

type bidDo struct{ gen.DO }

func (b bidDo) Debug() *bidDo {
	return b.withDO(b.DO.Debug())
}

func (b bidDo) WithContext(ctx context.Context) *bidDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidDo) ReadDB() *bidDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidDo) WriteDB() *bidDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidDo) Session(config *gorm.Session) *bidDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidDo) Clauses(conds ...clause.Expression) *bidDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidDo) Returning(value interface{}, columns ...string) *bidDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidDo) Not(conds ...gen.Condition) *bidDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidDo) Or(conds ...gen.Condition) *bidDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidDo) Select(conds ...field.Expr) *bidDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidDo) Where(conds ...gen.Condition) *bidDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidDo) Order(conds ...field.Expr) *bidDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidDo) Distinct(cols ...field.Expr) *bidDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidDo) Omit(cols ...field.Expr) *bidDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidDo) Join(table schema.Tabler, on ...field.Expr) *bidDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidDo) Group(cols ...field.Expr) *bidDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidDo) Having(conds ...gen.Condition) *bidDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidDo) Limit(limit int) *bidDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidDo) Offset(offset int) *bidDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidDo) Unscoped() *bidDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidDo) Create(values ...*model.Bid) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidDo) CreateInBatches(values []*model.Bid, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidDo) Save(values ...*model.Bid) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidDo) First() (*model.Bid, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bid), nil
	}
}

func (b bidDo) Take() (*model.Bid, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bid), nil
	}
}

func (b bidDo) Last() (*model.Bid, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bid), nil
	}
}

func (b bidDo) Find() ([]*model.Bid, error) {
	result, err := b.DO.Find()
	return result.([]*model.Bid), err
}

func (b bidDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Bid, err error) {
	buf := make([]*model.Bid, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidDo) FindInBatches(result *[]*model.Bid, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidDo) Attrs(attrs ...field.AssignExpr) *bidDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidDo) Assign(attrs ...field.AssignExpr) *bidDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidDo) Joins(fields ...field.RelationField) *bidDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidDo) Preload(fields ...field.RelationField) *bidDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidDo) FirstOrInit() (*model.Bid, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bid), nil
	}
}

func (b bidDo) FirstOrCreate() (*model.Bid, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Bid), nil
	}
}

func (b bidDo) FindByPage(offset int, limit int) (result []*model.Bid, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidDo) Delete(models ...*model.Bid) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidDo) withDO(do gen.Dao) *bidDo {
	b.DO = *do.(*gen.DO)
	return b
}
