// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newCartItem(db *gorm.DB, opts ...gen.DOOption) cartItem {
	_cartItem := cartItem{}

	_cartItem.cartItemDo.UseDB(db, opts...)
	_cartItem.cartItemDo.UseModel(&model.CartItem{})

	tableName := _cartItem.cartItemDo.TableName()
	_cartItem.ALL = field.NewAsterisk(tableName)
	_cartItem.CartItemID = field.NewInt32(tableName, "cart_item_id")
	_cartItem.CartID = field.NewString(tableName, "cart_id")
	_cartItem.ProductID = field.NewString(tableName, "product_id")
	_cartItem.VariantID = field.NewInt32(tableName, "variant_id")
	_cartItem.Quantity = field.NewInt32(tableName, "quantity")
	_cartItem.PriceSnapshot = field.NewFloat64(tableName, "price_snapshot")
	_cartItem.CreatedAt = field.NewTime(tableName, "created_at")
	_cartItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_cartItem.fillFieldMap()

	return _cartItem
}

type cartItem struct {
	cartItemDo cartItemDo

	ALL           field.Asterisk
	CartItemID    field.Int32
	CartID        field.String
	ProductID     field.String
	VariantID     field.Int32
	Quantity      field.Int32
	PriceSnapshot field.Float64
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (c cartItem) Table(newTableName string) *cartItem {
	c.cartItemDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cartItem) As(alias string) *cartItem {
	c.cartItemDo.DO = *(c.cartItemDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cartItem) updateTableName(table string) *cartItem {
	c.ALL = field.NewAsterisk(table)
	c.CartItemID = field.NewInt32(table, "cart_item_id")
	c.CartID = field.NewString(table, "cart_id")
	c.ProductID = field.NewString(table, "product_id")
	c.VariantID = field.NewInt32(table, "variant_id")
	c.Quantity = field.NewInt32(table, "quantity")
	c.PriceSnapshot = field.NewFloat64(table, "price_snapshot")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *cartItem) WithContext(ctx context.Context) *cartItemDo { return c.cartItemDo.WithContext(ctx) }

func (c cartItem) TableName() string { return c.cartItemDo.TableName() }

func (c cartItem) Alias() string { return c.cartItemDo.Alias() }

func (c cartItem) Columns(cols ...field.Expr) gen.Columns { return c.cartItemDo.Columns(cols...) }

func (c *cartItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cartItem) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["cart_item_id"] = c.CartItemID
	c.fieldMap["cart_id"] = c.CartID
	c.fieldMap["product_id"] = c.ProductID
	c.fieldMap["variant_id"] = c.VariantID
	c.fieldMap["quantity"] = c.Quantity
	c.fieldMap["price_snapshot"] = c.PriceSnapshot
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c cartItem) clone(db *gorm.DB) cartItem {
	c.cartItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cartItem) replaceDB(db *gorm.DB) cartItem {
	c.cartItemDo.ReplaceDB(db)
	return c
}

type cartItemDo struct{ gen.DO }

func (c cartItemDo) Debug() *cartItemDo {
	return c.withDO(c.DO.Debug())
}

func (c cartItemDo) WithContext(ctx context.Context) *cartItemDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cartItemDo) ReadDB() *cartItemDo {
	return c.Clauses(dbresolver.Read)
}

func (c cartItemDo) WriteDB() *cartItemDo {
	return c.Clauses(dbresolver.Write)
}

func (c cartItemDo) Session(config *gorm.Session) *cartItemDo {
	return c.withDO(c.DO.Session(config))
}

func (c cartItemDo) Clauses(conds ...clause.Expression) *cartItemDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cartItemDo) Returning(value interface{}, columns ...string) *cartItemDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cartItemDo) Not(conds ...gen.Condition) *cartItemDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cartItemDo) Or(conds ...gen.Condition) *cartItemDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cartItemDo) Select(conds ...field.Expr) *cartItemDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cartItemDo) Where(conds ...gen.Condition) *cartItemDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cartItemDo) Order(conds ...field.Expr) *cartItemDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cartItemDo) Distinct(cols ...field.Expr) *cartItemDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cartItemDo) Omit(cols ...field.Expr) *cartItemDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cartItemDo) Join(table schema.Tabler, on ...field.Expr) *cartItemDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cartItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cartItemDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cartItemDo) RightJoin(table schema.Tabler, on ...field.Expr) *cartItemDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cartItemDo) Group(cols ...field.Expr) *cartItemDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cartItemDo) Having(conds ...gen.Condition) *cartItemDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cartItemDo) Limit(limit int) *cartItemDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cartItemDo) Offset(offset int) *cartItemDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cartItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cartItemDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cartItemDo) Unscoped() *cartItemDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cartItemDo) Create(values ...*model.CartItem) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cartItemDo) CreateInBatches(values []*model.CartItem, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cartItemDo) Save(values ...*model.CartItem) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cartItemDo) First() (*model.CartItem, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartItem), nil
	}
}

func (c cartItemDo) Take() (*model.CartItem, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartItem), nil
	}
}

func (c cartItemDo) Last() (*model.CartItem, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartItem), nil
	}
}

func (c cartItemDo) Find() ([]*model.CartItem, error) {
	result, err := c.DO.Find()
	return result.([]*model.CartItem), err
}

func (c cartItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CartItem, err error) {
	buf := make([]*model.CartItem, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cartItemDo) FindInBatches(result *[]*model.CartItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cartItemDo) Attrs(attrs ...field.AssignExpr) *cartItemDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cartItemDo) Assign(attrs ...field.AssignExpr) *cartItemDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cartItemDo) Joins(fields ...field.RelationField) *cartItemDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cartItemDo) Preload(fields ...field.RelationField) *cartItemDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cartItemDo) FirstOrInit() (*model.CartItem, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartItem), nil
	}
}

func (c cartItemDo) FirstOrCreate() (*model.CartItem, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartItem), nil
	}
}

func (c cartItemDo) FindByPage(offset int, limit int) (result []*model.CartItem, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cartItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cartItemDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cartItemDo) Delete(models ...*model.CartItem) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cartItemDo) withDO(do gen.Dao) *cartItemDo {
	c.DO = *do.(*gen.DO)
	return c
}
