// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                      db,
		Auction:                 newAuction(db, opts...),
		Bid:                     newBid(db, opts...),
		Cart:                    newCart(db, opts...),
		CartItem:                newCartItem(db, opts...),
		Category:                newCategory(db, opts...),
		Notification:            newNotification(db, opts...),
		Order:                   newOrder(db, opts...),
		OrderItem:               newOrderItem(db, opts...),
		Payment:                 newPayment(db, opts...),
		Permission:              newPermission(db, opts...),
		Product:                 newProduct(db, opts...),
		ProductAttribute:        newProductAttribute(db, opts...),
		ProductMedium:           newProductMedium(db, opts...),
		ProductTag:              newProductTag(db, opts...),
		ProductVariant:          newProductVariant(db, opts...),
		Review:                  newReview(db, opts...),
		ReviewMedium:            newReviewMedium(db, opts...),
		Role:                    newRole(db, opts...),
		RolePermission:          newRolePermission(db, opts...),
		SchemaMigration:         newSchemaMigration(db, opts...),
		Shipment:                newShipment(db, opts...),
		ShipmentTrackingHistory: newShipmentTrackingHistory(db, opts...),
		Tag:                     newTag(db, opts...),
		User:                    newUser(db, opts...),
		UserAddress:             newUserAddress(db, opts...),
		UserRole:                newUserRole(db, opts...),
		Watchlist:               newWatchlist(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Auction                 auction
	Bid                     bid
	Cart                    cart
	CartItem                cartItem
	Category                category
	Notification            notification
	Order                   order
	OrderItem               orderItem
	Payment                 payment
	Permission              permission
	Product                 product
	ProductAttribute        productAttribute
	ProductMedium           productMedium
	ProductTag              productTag
	ProductVariant          productVariant
	Review                  review
	ReviewMedium            reviewMedium
	Role                    role
	RolePermission          rolePermission
	SchemaMigration         schemaMigration
	Shipment                shipment
	ShipmentTrackingHistory shipmentTrackingHistory
	Tag                     tag
	User                    user
	UserAddress             userAddress
	UserRole                userRole
	Watchlist               watchlist
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		Auction:                 q.Auction.clone(db),
		Bid:                     q.Bid.clone(db),
		Cart:                    q.Cart.clone(db),
		CartItem:                q.CartItem.clone(db),
		Category:                q.Category.clone(db),
		Notification:            q.Notification.clone(db),
		Order:                   q.Order.clone(db),
		OrderItem:               q.OrderItem.clone(db),
		Payment:                 q.Payment.clone(db),
		Permission:              q.Permission.clone(db),
		Product:                 q.Product.clone(db),
		ProductAttribute:        q.ProductAttribute.clone(db),
		ProductMedium:           q.ProductMedium.clone(db),
		ProductTag:              q.ProductTag.clone(db),
		ProductVariant:          q.ProductVariant.clone(db),
		Review:                  q.Review.clone(db),
		ReviewMedium:            q.ReviewMedium.clone(db),
		Role:                    q.Role.clone(db),
		RolePermission:          q.RolePermission.clone(db),
		SchemaMigration:         q.SchemaMigration.clone(db),
		Shipment:                q.Shipment.clone(db),
		ShipmentTrackingHistory: q.ShipmentTrackingHistory.clone(db),
		Tag:                     q.Tag.clone(db),
		User:                    q.User.clone(db),
		UserAddress:             q.UserAddress.clone(db),
		UserRole:                q.UserRole.clone(db),
		Watchlist:               q.Watchlist.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		Auction:                 q.Auction.replaceDB(db),
		Bid:                     q.Bid.replaceDB(db),
		Cart:                    q.Cart.replaceDB(db),
		CartItem:                q.CartItem.replaceDB(db),
		Category:                q.Category.replaceDB(db),
		Notification:            q.Notification.replaceDB(db),
		Order:                   q.Order.replaceDB(db),
		OrderItem:               q.OrderItem.replaceDB(db),
		Payment:                 q.Payment.replaceDB(db),
		Permission:              q.Permission.replaceDB(db),
		Product:                 q.Product.replaceDB(db),
		ProductAttribute:        q.ProductAttribute.replaceDB(db),
		ProductMedium:           q.ProductMedium.replaceDB(db),
		ProductTag:              q.ProductTag.replaceDB(db),
		ProductVariant:          q.ProductVariant.replaceDB(db),
		Review:                  q.Review.replaceDB(db),
		ReviewMedium:            q.ReviewMedium.replaceDB(db),
		Role:                    q.Role.replaceDB(db),
		RolePermission:          q.RolePermission.replaceDB(db),
		SchemaMigration:         q.SchemaMigration.replaceDB(db),
		Shipment:                q.Shipment.replaceDB(db),
		ShipmentTrackingHistory: q.ShipmentTrackingHistory.replaceDB(db),
		Tag:                     q.Tag.replaceDB(db),
		User:                    q.User.replaceDB(db),
		UserAddress:             q.UserAddress.replaceDB(db),
		UserRole:                q.UserRole.replaceDB(db),
		Watchlist:               q.Watchlist.replaceDB(db),
	}
}

type queryCtx struct {
	Auction                 *auctionDo
	Bid                     *bidDo
	Cart                    *cartDo
	CartItem                *cartItemDo
	Category                *categoryDo
	Notification            *notificationDo
	Order                   *orderDo
	OrderItem               *orderItemDo
	Payment                 *paymentDo
	Permission              *permissionDo
	Product                 *productDo
	ProductAttribute        *productAttributeDo
	ProductMedium           *productMediumDo
	ProductTag              *productTagDo
	ProductVariant          *productVariantDo
	Review                  *reviewDo
	ReviewMedium            *reviewMediumDo
	Role                    *roleDo
	RolePermission          *rolePermissionDo
	SchemaMigration         *schemaMigrationDo
	Shipment                *shipmentDo
	ShipmentTrackingHistory *shipmentTrackingHistoryDo
	Tag                     *tagDo
	User                    *userDo
	UserAddress             *userAddressDo
	UserRole                *userRoleDo
	Watchlist               *watchlistDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Auction:                 q.Auction.WithContext(ctx),
		Bid:                     q.Bid.WithContext(ctx),
		Cart:                    q.Cart.WithContext(ctx),
		CartItem:                q.CartItem.WithContext(ctx),
		Category:                q.Category.WithContext(ctx),
		Notification:            q.Notification.WithContext(ctx),
		Order:                   q.Order.WithContext(ctx),
		OrderItem:               q.OrderItem.WithContext(ctx),
		Payment:                 q.Payment.WithContext(ctx),
		Permission:              q.Permission.WithContext(ctx),
		Product:                 q.Product.WithContext(ctx),
		ProductAttribute:        q.ProductAttribute.WithContext(ctx),
		ProductMedium:           q.ProductMedium.WithContext(ctx),
		ProductTag:              q.ProductTag.WithContext(ctx),
		ProductVariant:          q.ProductVariant.WithContext(ctx),
		Review:                  q.Review.WithContext(ctx),
		ReviewMedium:            q.ReviewMedium.WithContext(ctx),
		Role:                    q.Role.WithContext(ctx),
		RolePermission:          q.RolePermission.WithContext(ctx),
		SchemaMigration:         q.SchemaMigration.WithContext(ctx),
		Shipment:                q.Shipment.WithContext(ctx),
		ShipmentTrackingHistory: q.ShipmentTrackingHistory.WithContext(ctx),
		Tag:                     q.Tag.WithContext(ctx),
		User:                    q.User.WithContext(ctx),
		UserAddress:             q.UserAddress.WithContext(ctx),
		UserRole:                q.UserRole.WithContext(ctx),
		Watchlist:               q.Watchlist.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
