// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newProductAttribute(db *gorm.DB, opts ...gen.DOOption) productAttribute {
	_productAttribute := productAttribute{}

	_productAttribute.productAttributeDo.UseDB(db, opts...)
	_productAttribute.productAttributeDo.UseModel(&model.ProductAttribute{})

	tableName := _productAttribute.productAttributeDo.TableName()
	_productAttribute.ALL = field.NewAsterisk(tableName)
	_productAttribute.AttributeID = field.NewInt32(tableName, "attribute_id")
	_productAttribute.ProductID = field.NewString(tableName, "product_id")
	_productAttribute.AttributeName = field.NewString(tableName, "attribute_name")
	_productAttribute.AttributeValue = field.NewString(tableName, "attribute_value")
	_productAttribute.CreatedAt = field.NewTime(tableName, "created_at")

	_productAttribute.fillFieldMap()

	return _productAttribute
}

type productAttribute struct {
	productAttributeDo productAttributeDo

	ALL            field.Asterisk
	AttributeID    field.Int32
	ProductID      field.String
	AttributeName  field.String
	AttributeValue field.String
	CreatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (p productAttribute) Table(newTableName string) *productAttribute {
	p.productAttributeDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productAttribute) As(alias string) *productAttribute {
	p.productAttributeDo.DO = *(p.productAttributeDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productAttribute) updateTableName(table string) *productAttribute {
	p.ALL = field.NewAsterisk(table)
	p.AttributeID = field.NewInt32(table, "attribute_id")
	p.ProductID = field.NewString(table, "product_id")
	p.AttributeName = field.NewString(table, "attribute_name")
	p.AttributeValue = field.NewString(table, "attribute_value")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *productAttribute) WithContext(ctx context.Context) *productAttributeDo {
	return p.productAttributeDo.WithContext(ctx)
}

func (p productAttribute) TableName() string { return p.productAttributeDo.TableName() }

func (p productAttribute) Alias() string { return p.productAttributeDo.Alias() }

func (p productAttribute) Columns(cols ...field.Expr) gen.Columns {
	return p.productAttributeDo.Columns(cols...)
}

func (p *productAttribute) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productAttribute) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["attribute_id"] = p.AttributeID
	p.fieldMap["product_id"] = p.ProductID
	p.fieldMap["attribute_name"] = p.AttributeName
	p.fieldMap["attribute_value"] = p.AttributeValue
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p productAttribute) clone(db *gorm.DB) productAttribute {
	p.productAttributeDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productAttribute) replaceDB(db *gorm.DB) productAttribute {
	p.productAttributeDo.ReplaceDB(db)
	return p
}

type productAttributeDo struct{ gen.DO }

func (p productAttributeDo) Debug() *productAttributeDo {
	return p.withDO(p.DO.Debug())
}

func (p productAttributeDo) WithContext(ctx context.Context) *productAttributeDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productAttributeDo) ReadDB() *productAttributeDo {
	return p.Clauses(dbresolver.Read)
}

func (p productAttributeDo) WriteDB() *productAttributeDo {
	return p.Clauses(dbresolver.Write)
}

func (p productAttributeDo) Session(config *gorm.Session) *productAttributeDo {
	return p.withDO(p.DO.Session(config))
}

func (p productAttributeDo) Clauses(conds ...clause.Expression) *productAttributeDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productAttributeDo) Returning(value interface{}, columns ...string) *productAttributeDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productAttributeDo) Not(conds ...gen.Condition) *productAttributeDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productAttributeDo) Or(conds ...gen.Condition) *productAttributeDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productAttributeDo) Select(conds ...field.Expr) *productAttributeDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productAttributeDo) Where(conds ...gen.Condition) *productAttributeDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productAttributeDo) Order(conds ...field.Expr) *productAttributeDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productAttributeDo) Distinct(cols ...field.Expr) *productAttributeDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productAttributeDo) Omit(cols ...field.Expr) *productAttributeDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productAttributeDo) Join(table schema.Tabler, on ...field.Expr) *productAttributeDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productAttributeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *productAttributeDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productAttributeDo) RightJoin(table schema.Tabler, on ...field.Expr) *productAttributeDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productAttributeDo) Group(cols ...field.Expr) *productAttributeDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productAttributeDo) Having(conds ...gen.Condition) *productAttributeDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productAttributeDo) Limit(limit int) *productAttributeDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productAttributeDo) Offset(offset int) *productAttributeDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productAttributeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *productAttributeDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productAttributeDo) Unscoped() *productAttributeDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productAttributeDo) Create(values ...*model.ProductAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productAttributeDo) CreateInBatches(values []*model.ProductAttribute, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productAttributeDo) Save(values ...*model.ProductAttribute) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productAttributeDo) First() (*model.ProductAttribute, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductAttribute), nil
	}
}

func (p productAttributeDo) Take() (*model.ProductAttribute, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductAttribute), nil
	}
}

func (p productAttributeDo) Last() (*model.ProductAttribute, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductAttribute), nil
	}
}

func (p productAttributeDo) Find() ([]*model.ProductAttribute, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductAttribute), err
}

func (p productAttributeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductAttribute, err error) {
	buf := make([]*model.ProductAttribute, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productAttributeDo) FindInBatches(result *[]*model.ProductAttribute, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productAttributeDo) Attrs(attrs ...field.AssignExpr) *productAttributeDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productAttributeDo) Assign(attrs ...field.AssignExpr) *productAttributeDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productAttributeDo) Joins(fields ...field.RelationField) *productAttributeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productAttributeDo) Preload(fields ...field.RelationField) *productAttributeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productAttributeDo) FirstOrInit() (*model.ProductAttribute, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductAttribute), nil
	}
}

func (p productAttributeDo) FirstOrCreate() (*model.ProductAttribute, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductAttribute), nil
	}
}

func (p productAttributeDo) FindByPage(offset int, limit int) (result []*model.ProductAttribute, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productAttributeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productAttributeDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productAttributeDo) Delete(models ...*model.ProductAttribute) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productAttributeDo) withDO(do gen.Dao) *productAttributeDo {
	p.DO = *do.(*gen.DO)
	return p
}
