// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newProductTag(db *gorm.DB, opts ...gen.DOOption) productTag {
	_productTag := productTag{}

	_productTag.productTagDo.UseDB(db, opts...)
	_productTag.productTagDo.UseModel(&model.ProductTag{})

	tableName := _productTag.productTagDo.TableName()
	_productTag.ALL = field.NewAsterisk(tableName)
	_productTag.ProductID = field.NewString(tableName, "product_id")
	_productTag.TagID = field.NewInt32(tableName, "tag_id")
	_productTag.CreatedAt = field.NewTime(tableName, "created_at")

	_productTag.fillFieldMap()

	return _productTag
}

type productTag struct {
	productTagDo productTagDo

	ALL       field.Asterisk
	ProductID field.String
	TagID     field.Int32
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p productTag) Table(newTableName string) *productTag {
	p.productTagDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productTag) As(alias string) *productTag {
	p.productTagDo.DO = *(p.productTagDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productTag) updateTableName(table string) *productTag {
	p.ALL = field.NewAsterisk(table)
	p.ProductID = field.NewString(table, "product_id")
	p.TagID = field.NewInt32(table, "tag_id")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *productTag) WithContext(ctx context.Context) *productTagDo {
	return p.productTagDo.WithContext(ctx)
}

func (p productTag) TableName() string { return p.productTagDo.TableName() }

func (p productTag) Alias() string { return p.productTagDo.Alias() }

func (p productTag) Columns(cols ...field.Expr) gen.Columns { return p.productTagDo.Columns(cols...) }

func (p *productTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productTag) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["product_id"] = p.ProductID
	p.fieldMap["tag_id"] = p.TagID
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p productTag) clone(db *gorm.DB) productTag {
	p.productTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productTag) replaceDB(db *gorm.DB) productTag {
	p.productTagDo.ReplaceDB(db)
	return p
}

type productTagDo struct{ gen.DO }

func (p productTagDo) Debug() *productTagDo {
	return p.withDO(p.DO.Debug())
}

func (p productTagDo) WithContext(ctx context.Context) *productTagDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productTagDo) ReadDB() *productTagDo {
	return p.Clauses(dbresolver.Read)
}

func (p productTagDo) WriteDB() *productTagDo {
	return p.Clauses(dbresolver.Write)
}

func (p productTagDo) Session(config *gorm.Session) *productTagDo {
	return p.withDO(p.DO.Session(config))
}

func (p productTagDo) Clauses(conds ...clause.Expression) *productTagDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productTagDo) Returning(value interface{}, columns ...string) *productTagDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productTagDo) Not(conds ...gen.Condition) *productTagDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productTagDo) Or(conds ...gen.Condition) *productTagDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productTagDo) Select(conds ...field.Expr) *productTagDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productTagDo) Where(conds ...gen.Condition) *productTagDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productTagDo) Order(conds ...field.Expr) *productTagDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productTagDo) Distinct(cols ...field.Expr) *productTagDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productTagDo) Omit(cols ...field.Expr) *productTagDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productTagDo) Join(table schema.Tabler, on ...field.Expr) *productTagDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *productTagDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *productTagDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productTagDo) Group(cols ...field.Expr) *productTagDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productTagDo) Having(conds ...gen.Condition) *productTagDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productTagDo) Limit(limit int) *productTagDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productTagDo) Offset(offset int) *productTagDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *productTagDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productTagDo) Unscoped() *productTagDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productTagDo) Create(values ...*model.ProductTag) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productTagDo) CreateInBatches(values []*model.ProductTag, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productTagDo) Save(values ...*model.ProductTag) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productTagDo) First() (*model.ProductTag, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTag), nil
	}
}

func (p productTagDo) Take() (*model.ProductTag, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTag), nil
	}
}

func (p productTagDo) Last() (*model.ProductTag, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTag), nil
	}
}

func (p productTagDo) Find() ([]*model.ProductTag, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductTag), err
}

func (p productTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductTag, err error) {
	buf := make([]*model.ProductTag, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productTagDo) FindInBatches(result *[]*model.ProductTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productTagDo) Attrs(attrs ...field.AssignExpr) *productTagDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productTagDo) Assign(attrs ...field.AssignExpr) *productTagDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productTagDo) Joins(fields ...field.RelationField) *productTagDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productTagDo) Preload(fields ...field.RelationField) *productTagDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productTagDo) FirstOrInit() (*model.ProductTag, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTag), nil
	}
}

func (p productTagDo) FirstOrCreate() (*model.ProductTag, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTag), nil
	}
}

func (p productTagDo) FindByPage(offset int, limit int) (result []*model.ProductTag, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productTagDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productTagDo) Delete(models ...*model.ProductTag) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productTagDo) withDO(do gen.Dao) *productTagDo {
	p.DO = *do.(*gen.DO)
	return p
}
