// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newProductMedium(db *gorm.DB, opts ...gen.DOOption) productMedium {
	_productMedium := productMedium{}

	_productMedium.productMediumDo.UseDB(db, opts...)
	_productMedium.productMediumDo.UseModel(&model.ProductMedium{})

	tableName := _productMedium.productMediumDo.TableName()
	_productMedium.ALL = field.NewAsterisk(tableName)
	_productMedium.MediaID = field.NewInt32(tableName, "media_id")
	_productMedium.ProductID = field.NewString(tableName, "product_id")
	_productMedium.MediaType = field.NewString(tableName, "media_type")
	_productMedium.MediaURL = field.NewString(tableName, "media_url")
	_productMedium.ThumbnailURL = field.NewString(tableName, "thumbnail_url")
	_productMedium.AltText = field.NewString(tableName, "alt_text")
	_productMedium.SortOrder = field.NewInt32(tableName, "sort_order")
	_productMedium.IsPrimary = field.NewBool(tableName, "is_primary")
	_productMedium.CreatedAt = field.NewTime(tableName, "created_at")

	_productMedium.fillFieldMap()

	return _productMedium
}

type productMedium struct {
	productMediumDo productMediumDo

	ALL          field.Asterisk
	MediaID      field.Int32
	ProductID    field.String
	MediaType    field.String
	MediaURL     field.String
	ThumbnailURL field.String
	AltText      field.String
	SortOrder    field.Int32
	IsPrimary    field.Bool
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (p productMedium) Table(newTableName string) *productMedium {
	p.productMediumDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productMedium) As(alias string) *productMedium {
	p.productMediumDo.DO = *(p.productMediumDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productMedium) updateTableName(table string) *productMedium {
	p.ALL = field.NewAsterisk(table)
	p.MediaID = field.NewInt32(table, "media_id")
	p.ProductID = field.NewString(table, "product_id")
	p.MediaType = field.NewString(table, "media_type")
	p.MediaURL = field.NewString(table, "media_url")
	p.ThumbnailURL = field.NewString(table, "thumbnail_url")
	p.AltText = field.NewString(table, "alt_text")
	p.SortOrder = field.NewInt32(table, "sort_order")
	p.IsPrimary = field.NewBool(table, "is_primary")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *productMedium) WithContext(ctx context.Context) *productMediumDo {
	return p.productMediumDo.WithContext(ctx)
}

func (p productMedium) TableName() string { return p.productMediumDo.TableName() }

func (p productMedium) Alias() string { return p.productMediumDo.Alias() }

func (p productMedium) Columns(cols ...field.Expr) gen.Columns {
	return p.productMediumDo.Columns(cols...)
}

func (p *productMedium) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productMedium) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["media_id"] = p.MediaID
	p.fieldMap["product_id"] = p.ProductID
	p.fieldMap["media_type"] = p.MediaType
	p.fieldMap["media_url"] = p.MediaURL
	p.fieldMap["thumbnail_url"] = p.ThumbnailURL
	p.fieldMap["alt_text"] = p.AltText
	p.fieldMap["sort_order"] = p.SortOrder
	p.fieldMap["is_primary"] = p.IsPrimary
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p productMedium) clone(db *gorm.DB) productMedium {
	p.productMediumDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productMedium) replaceDB(db *gorm.DB) productMedium {
	p.productMediumDo.ReplaceDB(db)
	return p
}

type productMediumDo struct{ gen.DO }

func (p productMediumDo) Debug() *productMediumDo {
	return p.withDO(p.DO.Debug())
}

func (p productMediumDo) WithContext(ctx context.Context) *productMediumDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productMediumDo) ReadDB() *productMediumDo {
	return p.Clauses(dbresolver.Read)
}

func (p productMediumDo) WriteDB() *productMediumDo {
	return p.Clauses(dbresolver.Write)
}

func (p productMediumDo) Session(config *gorm.Session) *productMediumDo {
	return p.withDO(p.DO.Session(config))
}

func (p productMediumDo) Clauses(conds ...clause.Expression) *productMediumDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productMediumDo) Returning(value interface{}, columns ...string) *productMediumDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productMediumDo) Not(conds ...gen.Condition) *productMediumDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productMediumDo) Or(conds ...gen.Condition) *productMediumDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productMediumDo) Select(conds ...field.Expr) *productMediumDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productMediumDo) Where(conds ...gen.Condition) *productMediumDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productMediumDo) Order(conds ...field.Expr) *productMediumDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productMediumDo) Distinct(cols ...field.Expr) *productMediumDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productMediumDo) Omit(cols ...field.Expr) *productMediumDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productMediumDo) Join(table schema.Tabler, on ...field.Expr) *productMediumDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productMediumDo) LeftJoin(table schema.Tabler, on ...field.Expr) *productMediumDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productMediumDo) RightJoin(table schema.Tabler, on ...field.Expr) *productMediumDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productMediumDo) Group(cols ...field.Expr) *productMediumDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productMediumDo) Having(conds ...gen.Condition) *productMediumDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productMediumDo) Limit(limit int) *productMediumDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productMediumDo) Offset(offset int) *productMediumDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productMediumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *productMediumDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productMediumDo) Unscoped() *productMediumDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productMediumDo) Create(values ...*model.ProductMedium) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productMediumDo) CreateInBatches(values []*model.ProductMedium, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productMediumDo) Save(values ...*model.ProductMedium) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productMediumDo) First() (*model.ProductMedium, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) Take() (*model.ProductMedium, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) Last() (*model.ProductMedium, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) Find() ([]*model.ProductMedium, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductMedium), err
}

func (p productMediumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductMedium, err error) {
	buf := make([]*model.ProductMedium, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productMediumDo) FindInBatches(result *[]*model.ProductMedium, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productMediumDo) Attrs(attrs ...field.AssignExpr) *productMediumDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productMediumDo) Assign(attrs ...field.AssignExpr) *productMediumDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productMediumDo) Joins(fields ...field.RelationField) *productMediumDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productMediumDo) Preload(fields ...field.RelationField) *productMediumDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productMediumDo) FirstOrInit() (*model.ProductMedium, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) FirstOrCreate() (*model.ProductMedium, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductMedium), nil
	}
}

func (p productMediumDo) FindByPage(offset int, limit int) (result []*model.ProductMedium, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productMediumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productMediumDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productMediumDo) Delete(models ...*model.ProductMedium) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productMediumDo) withDO(do gen.Dao) *productMediumDo {
	p.DO = *do.(*gen.DO)
	return p
}
