// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newReviewMedium(db *gorm.DB, opts ...gen.DOOption) reviewMedium {
	_reviewMedium := reviewMedium{}

	_reviewMedium.reviewMediumDo.UseDB(db, opts...)
	_reviewMedium.reviewMediumDo.UseModel(&model.ReviewMedium{})

	tableName := _reviewMedium.reviewMediumDo.TableName()
	_reviewMedium.ALL = field.NewAsterisk(tableName)
	_reviewMedium.ReviewMediaID = field.NewInt32(tableName, "review_media_id")
	_reviewMedium.ReviewID = field.NewString(tableName, "review_id")
	_reviewMedium.MediaType = field.NewString(tableName, "media_type")
	_reviewMedium.MediaURL = field.NewString(tableName, "media_url")
	_reviewMedium.CreatedAt = field.NewTime(tableName, "created_at")

	_reviewMedium.fillFieldMap()

	return _reviewMedium
}

type reviewMedium struct {
	reviewMediumDo reviewMediumDo

	ALL           field.Asterisk
	ReviewMediaID field.Int32
	ReviewID      field.String
	MediaType     field.String
	MediaURL      field.String
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (r reviewMedium) Table(newTableName string) *reviewMedium {
	r.reviewMediumDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reviewMedium) As(alias string) *reviewMedium {
	r.reviewMediumDo.DO = *(r.reviewMediumDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reviewMedium) updateTableName(table string) *reviewMedium {
	r.ALL = field.NewAsterisk(table)
	r.ReviewMediaID = field.NewInt32(table, "review_media_id")
	r.ReviewID = field.NewString(table, "review_id")
	r.MediaType = field.NewString(table, "media_type")
	r.MediaURL = field.NewString(table, "media_url")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *reviewMedium) WithContext(ctx context.Context) *reviewMediumDo {
	return r.reviewMediumDo.WithContext(ctx)
}

func (r reviewMedium) TableName() string { return r.reviewMediumDo.TableName() }

func (r reviewMedium) Alias() string { return r.reviewMediumDo.Alias() }

func (r reviewMedium) Columns(cols ...field.Expr) gen.Columns {
	return r.reviewMediumDo.Columns(cols...)
}

func (r *reviewMedium) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reviewMedium) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["review_media_id"] = r.ReviewMediaID
	r.fieldMap["review_id"] = r.ReviewID
	r.fieldMap["media_type"] = r.MediaType
	r.fieldMap["media_url"] = r.MediaURL
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r reviewMedium) clone(db *gorm.DB) reviewMedium {
	r.reviewMediumDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reviewMedium) replaceDB(db *gorm.DB) reviewMedium {
	r.reviewMediumDo.ReplaceDB(db)
	return r
}

type reviewMediumDo struct{ gen.DO }

func (r reviewMediumDo) Debug() *reviewMediumDo {
	return r.withDO(r.DO.Debug())
}

func (r reviewMediumDo) WithContext(ctx context.Context) *reviewMediumDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reviewMediumDo) ReadDB() *reviewMediumDo {
	return r.Clauses(dbresolver.Read)
}

func (r reviewMediumDo) WriteDB() *reviewMediumDo {
	return r.Clauses(dbresolver.Write)
}

func (r reviewMediumDo) Session(config *gorm.Session) *reviewMediumDo {
	return r.withDO(r.DO.Session(config))
}

func (r reviewMediumDo) Clauses(conds ...clause.Expression) *reviewMediumDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reviewMediumDo) Returning(value interface{}, columns ...string) *reviewMediumDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reviewMediumDo) Not(conds ...gen.Condition) *reviewMediumDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reviewMediumDo) Or(conds ...gen.Condition) *reviewMediumDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reviewMediumDo) Select(conds ...field.Expr) *reviewMediumDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reviewMediumDo) Where(conds ...gen.Condition) *reviewMediumDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reviewMediumDo) Order(conds ...field.Expr) *reviewMediumDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reviewMediumDo) Distinct(cols ...field.Expr) *reviewMediumDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reviewMediumDo) Omit(cols ...field.Expr) *reviewMediumDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reviewMediumDo) Join(table schema.Tabler, on ...field.Expr) *reviewMediumDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reviewMediumDo) LeftJoin(table schema.Tabler, on ...field.Expr) *reviewMediumDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reviewMediumDo) RightJoin(table schema.Tabler, on ...field.Expr) *reviewMediumDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reviewMediumDo) Group(cols ...field.Expr) *reviewMediumDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reviewMediumDo) Having(conds ...gen.Condition) *reviewMediumDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reviewMediumDo) Limit(limit int) *reviewMediumDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reviewMediumDo) Offset(offset int) *reviewMediumDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reviewMediumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *reviewMediumDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reviewMediumDo) Unscoped() *reviewMediumDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reviewMediumDo) Create(values ...*model.ReviewMedium) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reviewMediumDo) CreateInBatches(values []*model.ReviewMedium, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reviewMediumDo) Save(values ...*model.ReviewMedium) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reviewMediumDo) First() (*model.ReviewMedium, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReviewMedium), nil
	}
}

func (r reviewMediumDo) Take() (*model.ReviewMedium, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReviewMedium), nil
	}
}

func (r reviewMediumDo) Last() (*model.ReviewMedium, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReviewMedium), nil
	}
}

func (r reviewMediumDo) Find() ([]*model.ReviewMedium, error) {
	result, err := r.DO.Find()
	return result.([]*model.ReviewMedium), err
}

func (r reviewMediumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReviewMedium, err error) {
	buf := make([]*model.ReviewMedium, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reviewMediumDo) FindInBatches(result *[]*model.ReviewMedium, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reviewMediumDo) Attrs(attrs ...field.AssignExpr) *reviewMediumDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reviewMediumDo) Assign(attrs ...field.AssignExpr) *reviewMediumDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reviewMediumDo) Joins(fields ...field.RelationField) *reviewMediumDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reviewMediumDo) Preload(fields ...field.RelationField) *reviewMediumDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reviewMediumDo) FirstOrInit() (*model.ReviewMedium, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReviewMedium), nil
	}
}

func (r reviewMediumDo) FirstOrCreate() (*model.ReviewMedium, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReviewMedium), nil
	}
}

func (r reviewMediumDo) FindByPage(offset int, limit int) (result []*model.ReviewMedium, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reviewMediumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reviewMediumDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reviewMediumDo) Delete(models ...*model.ReviewMedium) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reviewMediumDo) withDO(do gen.Dao) *reviewMediumDo {
	r.DO = *do.(*gen.DO)
	return r
}
