// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newShipment(db *gorm.DB, opts ...gen.DOOption) shipment {
	_shipment := shipment{}

	_shipment.shipmentDo.UseDB(db, opts...)
	_shipment.shipmentDo.UseModel(&model.Shipment{})

	tableName := _shipment.shipmentDo.TableName()
	_shipment.ALL = field.NewAsterisk(tableName)
	_shipment.ShipmentID = field.NewInt32(tableName, "shipment_id")
	_shipment.OrderID = field.NewString(tableName, "order_id")
	_shipment.Carrier = field.NewString(tableName, "carrier")
	_shipment.TrackingNumber = field.NewString(tableName, "tracking_number")
	_shipment.ShippingMethod = field.NewString(tableName, "shipping_method")
	_shipment.EstimatedDelivery = field.NewTime(tableName, "estimated_delivery")
	_shipment.ActualDelivery = field.NewTime(tableName, "actual_delivery")
	_shipment.ShipmentStatus = field.NewString(tableName, "shipment_status")
	_shipment.ShippedAt = field.NewTime(tableName, "shipped_at")
	_shipment.CreatedAt = field.NewTime(tableName, "created_at")
	_shipment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_shipment.DeletedAt = field.NewField(tableName, "deleted_at")

	_shipment.fillFieldMap()

	return _shipment
}

type shipment struct {
	shipmentDo shipmentDo

	ALL               field.Asterisk
	ShipmentID        field.Int32
	OrderID           field.String
	Carrier           field.String
	TrackingNumber    field.String
	ShippingMethod    field.String
	EstimatedDelivery field.Time
	ActualDelivery    field.Time
	ShipmentStatus    field.String
	ShippedAt         field.Time
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field

	fieldMap map[string]field.Expr
}

func (s shipment) Table(newTableName string) *shipment {
	s.shipmentDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shipment) As(alias string) *shipment {
	s.shipmentDo.DO = *(s.shipmentDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shipment) updateTableName(table string) *shipment {
	s.ALL = field.NewAsterisk(table)
	s.ShipmentID = field.NewInt32(table, "shipment_id")
	s.OrderID = field.NewString(table, "order_id")
	s.Carrier = field.NewString(table, "carrier")
	s.TrackingNumber = field.NewString(table, "tracking_number")
	s.ShippingMethod = field.NewString(table, "shipping_method")
	s.EstimatedDelivery = field.NewTime(table, "estimated_delivery")
	s.ActualDelivery = field.NewTime(table, "actual_delivery")
	s.ShipmentStatus = field.NewString(table, "shipment_status")
	s.ShippedAt = field.NewTime(table, "shipped_at")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *shipment) WithContext(ctx context.Context) *shipmentDo { return s.shipmentDo.WithContext(ctx) }

func (s shipment) TableName() string { return s.shipmentDo.TableName() }

func (s shipment) Alias() string { return s.shipmentDo.Alias() }

func (s shipment) Columns(cols ...field.Expr) gen.Columns { return s.shipmentDo.Columns(cols...) }

func (s *shipment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shipment) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["shipment_id"] = s.ShipmentID
	s.fieldMap["order_id"] = s.OrderID
	s.fieldMap["carrier"] = s.Carrier
	s.fieldMap["tracking_number"] = s.TrackingNumber
	s.fieldMap["shipping_method"] = s.ShippingMethod
	s.fieldMap["estimated_delivery"] = s.EstimatedDelivery
	s.fieldMap["actual_delivery"] = s.ActualDelivery
	s.fieldMap["shipment_status"] = s.ShipmentStatus
	s.fieldMap["shipped_at"] = s.ShippedAt
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s shipment) clone(db *gorm.DB) shipment {
	s.shipmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shipment) replaceDB(db *gorm.DB) shipment {
	s.shipmentDo.ReplaceDB(db)
	return s
}

type shipmentDo struct{ gen.DO }

func (s shipmentDo) Debug() *shipmentDo {
	return s.withDO(s.DO.Debug())
}

func (s shipmentDo) WithContext(ctx context.Context) *shipmentDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shipmentDo) ReadDB() *shipmentDo {
	return s.Clauses(dbresolver.Read)
}

func (s shipmentDo) WriteDB() *shipmentDo {
	return s.Clauses(dbresolver.Write)
}

func (s shipmentDo) Session(config *gorm.Session) *shipmentDo {
	return s.withDO(s.DO.Session(config))
}

func (s shipmentDo) Clauses(conds ...clause.Expression) *shipmentDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shipmentDo) Returning(value interface{}, columns ...string) *shipmentDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shipmentDo) Not(conds ...gen.Condition) *shipmentDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shipmentDo) Or(conds ...gen.Condition) *shipmentDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shipmentDo) Select(conds ...field.Expr) *shipmentDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shipmentDo) Where(conds ...gen.Condition) *shipmentDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shipmentDo) Order(conds ...field.Expr) *shipmentDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shipmentDo) Distinct(cols ...field.Expr) *shipmentDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shipmentDo) Omit(cols ...field.Expr) *shipmentDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shipmentDo) Join(table schema.Tabler, on ...field.Expr) *shipmentDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shipmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *shipmentDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shipmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *shipmentDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shipmentDo) Group(cols ...field.Expr) *shipmentDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shipmentDo) Having(conds ...gen.Condition) *shipmentDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shipmentDo) Limit(limit int) *shipmentDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shipmentDo) Offset(offset int) *shipmentDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shipmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *shipmentDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shipmentDo) Unscoped() *shipmentDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shipmentDo) Create(values ...*model.Shipment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shipmentDo) CreateInBatches(values []*model.Shipment, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shipmentDo) Save(values ...*model.Shipment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shipmentDo) First() (*model.Shipment, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shipment), nil
	}
}

func (s shipmentDo) Take() (*model.Shipment, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shipment), nil
	}
}

func (s shipmentDo) Last() (*model.Shipment, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shipment), nil
	}
}

func (s shipmentDo) Find() ([]*model.Shipment, error) {
	result, err := s.DO.Find()
	return result.([]*model.Shipment), err
}

func (s shipmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Shipment, err error) {
	buf := make([]*model.Shipment, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shipmentDo) FindInBatches(result *[]*model.Shipment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shipmentDo) Attrs(attrs ...field.AssignExpr) *shipmentDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shipmentDo) Assign(attrs ...field.AssignExpr) *shipmentDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shipmentDo) Joins(fields ...field.RelationField) *shipmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shipmentDo) Preload(fields ...field.RelationField) *shipmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shipmentDo) FirstOrInit() (*model.Shipment, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shipment), nil
	}
}

func (s shipmentDo) FirstOrCreate() (*model.Shipment, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Shipment), nil
	}
}

func (s shipmentDo) FindByPage(offset int, limit int) (result []*model.Shipment, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shipmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shipmentDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shipmentDo) Delete(models ...*model.Shipment) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shipmentDo) withDO(do gen.Dao) *shipmentDo {
	s.DO = *do.(*gen.DO)
	return s
}
