// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newShipmentTrackingHistory(db *gorm.DB, opts ...gen.DOOption) shipmentTrackingHistory {
	_shipmentTrackingHistory := shipmentTrackingHistory{}

	_shipmentTrackingHistory.shipmentTrackingHistoryDo.UseDB(db, opts...)
	_shipmentTrackingHistory.shipmentTrackingHistoryDo.UseModel(&model.ShipmentTrackingHistory{})

	tableName := _shipmentTrackingHistory.shipmentTrackingHistoryDo.TableName()
	_shipmentTrackingHistory.ALL = field.NewAsterisk(tableName)
	_shipmentTrackingHistory.TrackingHistoryID = field.NewInt32(tableName, "tracking_history_id")
	_shipmentTrackingHistory.ShipmentID = field.NewInt32(tableName, "shipment_id")
	_shipmentTrackingHistory.Status = field.NewString(tableName, "status")
	_shipmentTrackingHistory.Location = field.NewString(tableName, "location")
	_shipmentTrackingHistory.Description = field.NewString(tableName, "description")
	_shipmentTrackingHistory.TrackedAt = field.NewTime(tableName, "tracked_at")
	_shipmentTrackingHistory.CreatedAt = field.NewTime(tableName, "created_at")

	_shipmentTrackingHistory.fillFieldMap()

	return _shipmentTrackingHistory
}

type shipmentTrackingHistory struct {
	shipmentTrackingHistoryDo shipmentTrackingHistoryDo

	ALL               field.Asterisk
	TrackingHistoryID field.Int32
	ShipmentID        field.Int32
	Status            field.String
	Location          field.String
	Description       field.String
	TrackedAt         field.Time
	CreatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (s shipmentTrackingHistory) Table(newTableName string) *shipmentTrackingHistory {
	s.shipmentTrackingHistoryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shipmentTrackingHistory) As(alias string) *shipmentTrackingHistory {
	s.shipmentTrackingHistoryDo.DO = *(s.shipmentTrackingHistoryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shipmentTrackingHistory) updateTableName(table string) *shipmentTrackingHistory {
	s.ALL = field.NewAsterisk(table)
	s.TrackingHistoryID = field.NewInt32(table, "tracking_history_id")
	s.ShipmentID = field.NewInt32(table, "shipment_id")
	s.Status = field.NewString(table, "status")
	s.Location = field.NewString(table, "location")
	s.Description = field.NewString(table, "description")
	s.TrackedAt = field.NewTime(table, "tracked_at")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *shipmentTrackingHistory) WithContext(ctx context.Context) *shipmentTrackingHistoryDo {
	return s.shipmentTrackingHistoryDo.WithContext(ctx)
}

func (s shipmentTrackingHistory) TableName() string { return s.shipmentTrackingHistoryDo.TableName() }

func (s shipmentTrackingHistory) Alias() string { return s.shipmentTrackingHistoryDo.Alias() }

func (s shipmentTrackingHistory) Columns(cols ...field.Expr) gen.Columns {
	return s.shipmentTrackingHistoryDo.Columns(cols...)
}

func (s *shipmentTrackingHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shipmentTrackingHistory) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["tracking_history_id"] = s.TrackingHistoryID
	s.fieldMap["shipment_id"] = s.ShipmentID
	s.fieldMap["status"] = s.Status
	s.fieldMap["location"] = s.Location
	s.fieldMap["description"] = s.Description
	s.fieldMap["tracked_at"] = s.TrackedAt
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s shipmentTrackingHistory) clone(db *gorm.DB) shipmentTrackingHistory {
	s.shipmentTrackingHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shipmentTrackingHistory) replaceDB(db *gorm.DB) shipmentTrackingHistory {
	s.shipmentTrackingHistoryDo.ReplaceDB(db)
	return s
}

type shipmentTrackingHistoryDo struct{ gen.DO }

func (s shipmentTrackingHistoryDo) Debug() *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Debug())
}

func (s shipmentTrackingHistoryDo) WithContext(ctx context.Context) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shipmentTrackingHistoryDo) ReadDB() *shipmentTrackingHistoryDo {
	return s.Clauses(dbresolver.Read)
}

func (s shipmentTrackingHistoryDo) WriteDB() *shipmentTrackingHistoryDo {
	return s.Clauses(dbresolver.Write)
}

func (s shipmentTrackingHistoryDo) Session(config *gorm.Session) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Session(config))
}

func (s shipmentTrackingHistoryDo) Clauses(conds ...clause.Expression) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shipmentTrackingHistoryDo) Returning(value interface{}, columns ...string) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shipmentTrackingHistoryDo) Not(conds ...gen.Condition) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shipmentTrackingHistoryDo) Or(conds ...gen.Condition) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shipmentTrackingHistoryDo) Select(conds ...field.Expr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shipmentTrackingHistoryDo) Where(conds ...gen.Condition) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shipmentTrackingHistoryDo) Order(conds ...field.Expr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shipmentTrackingHistoryDo) Distinct(cols ...field.Expr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shipmentTrackingHistoryDo) Omit(cols ...field.Expr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shipmentTrackingHistoryDo) Join(table schema.Tabler, on ...field.Expr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shipmentTrackingHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shipmentTrackingHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shipmentTrackingHistoryDo) Group(cols ...field.Expr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shipmentTrackingHistoryDo) Having(conds ...gen.Condition) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shipmentTrackingHistoryDo) Limit(limit int) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shipmentTrackingHistoryDo) Offset(offset int) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shipmentTrackingHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shipmentTrackingHistoryDo) Unscoped() *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shipmentTrackingHistoryDo) Create(values ...*model.ShipmentTrackingHistory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shipmentTrackingHistoryDo) CreateInBatches(values []*model.ShipmentTrackingHistory, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shipmentTrackingHistoryDo) Save(values ...*model.ShipmentTrackingHistory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shipmentTrackingHistoryDo) First() (*model.ShipmentTrackingHistory, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipmentTrackingHistory), nil
	}
}

func (s shipmentTrackingHistoryDo) Take() (*model.ShipmentTrackingHistory, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipmentTrackingHistory), nil
	}
}

func (s shipmentTrackingHistoryDo) Last() (*model.ShipmentTrackingHistory, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipmentTrackingHistory), nil
	}
}

func (s shipmentTrackingHistoryDo) Find() ([]*model.ShipmentTrackingHistory, error) {
	result, err := s.DO.Find()
	return result.([]*model.ShipmentTrackingHistory), err
}

func (s shipmentTrackingHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ShipmentTrackingHistory, err error) {
	buf := make([]*model.ShipmentTrackingHistory, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shipmentTrackingHistoryDo) FindInBatches(result *[]*model.ShipmentTrackingHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shipmentTrackingHistoryDo) Attrs(attrs ...field.AssignExpr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shipmentTrackingHistoryDo) Assign(attrs ...field.AssignExpr) *shipmentTrackingHistoryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shipmentTrackingHistoryDo) Joins(fields ...field.RelationField) *shipmentTrackingHistoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shipmentTrackingHistoryDo) Preload(fields ...field.RelationField) *shipmentTrackingHistoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shipmentTrackingHistoryDo) FirstOrInit() (*model.ShipmentTrackingHistory, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipmentTrackingHistory), nil
	}
}

func (s shipmentTrackingHistoryDo) FirstOrCreate() (*model.ShipmentTrackingHistory, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShipmentTrackingHistory), nil
	}
}

func (s shipmentTrackingHistoryDo) FindByPage(offset int, limit int) (result []*model.ShipmentTrackingHistory, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shipmentTrackingHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shipmentTrackingHistoryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shipmentTrackingHistoryDo) Delete(models ...*model.ShipmentTrackingHistory) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shipmentTrackingHistoryDo) withDO(do gen.Dao) *shipmentTrackingHistoryDo {
	s.DO = *do.(*gen.DO)
	return s
}
