// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/parxyws/nego-gin/dao/model"
)

func newUserAddress(db *gorm.DB, opts ...gen.DOOption) userAddress {
	_userAddress := userAddress{}

	_userAddress.userAddressDo.UseDB(db, opts...)
	_userAddress.userAddressDo.UseModel(&model.UserAddress{})

	tableName := _userAddress.userAddressDo.TableName()
	_userAddress.ALL = field.NewAsterisk(tableName)
	_userAddress.AddressID = field.NewInt32(tableName, "address_id")
	_userAddress.UserID = field.NewString(tableName, "user_id")
	_userAddress.AddressType = field.NewString(tableName, "address_type")
	_userAddress.IsDefault = field.NewBool(tableName, "is_default")
	_userAddress.RecipientName = field.NewString(tableName, "recipient_name")
	_userAddress.AddressLine1 = field.NewString(tableName, "address_line1")
	_userAddress.AddressLine2 = field.NewString(tableName, "address_line2")
	_userAddress.City = field.NewString(tableName, "city")
	_userAddress.StateProvince = field.NewString(tableName, "state_province")
	_userAddress.PostalCode = field.NewString(tableName, "postal_code")
	_userAddress.CountryCode = field.NewString(tableName, "country_code")
	_userAddress.Phone = field.NewString(tableName, "phone")
	_userAddress.CreatedAt = field.NewTime(tableName, "created_at")
	_userAddress.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userAddress.DeletedAt = field.NewField(tableName, "deleted_at")

	_userAddress.fillFieldMap()

	return _userAddress
}

type userAddress struct {
	userAddressDo userAddressDo

	ALL           field.Asterisk
	AddressID     field.Int32
	UserID        field.String
	AddressType   field.String
	IsDefault     field.Bool
	RecipientName field.String
	AddressLine1  field.String
	AddressLine2  field.String
	City          field.String
	StateProvince field.String
	PostalCode    field.String
	CountryCode   field.String
	Phone         field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field

	fieldMap map[string]field.Expr
}

func (u userAddress) Table(newTableName string) *userAddress {
	u.userAddressDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userAddress) As(alias string) *userAddress {
	u.userAddressDo.DO = *(u.userAddressDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userAddress) updateTableName(table string) *userAddress {
	u.ALL = field.NewAsterisk(table)
	u.AddressID = field.NewInt32(table, "address_id")
	u.UserID = field.NewString(table, "user_id")
	u.AddressType = field.NewString(table, "address_type")
	u.IsDefault = field.NewBool(table, "is_default")
	u.RecipientName = field.NewString(table, "recipient_name")
	u.AddressLine1 = field.NewString(table, "address_line1")
	u.AddressLine2 = field.NewString(table, "address_line2")
	u.City = field.NewString(table, "city")
	u.StateProvince = field.NewString(table, "state_province")
	u.PostalCode = field.NewString(table, "postal_code")
	u.CountryCode = field.NewString(table, "country_code")
	u.Phone = field.NewString(table, "phone")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *userAddress) WithContext(ctx context.Context) *userAddressDo {
	return u.userAddressDo.WithContext(ctx)
}

func (u userAddress) TableName() string { return u.userAddressDo.TableName() }

func (u userAddress) Alias() string { return u.userAddressDo.Alias() }

func (u userAddress) Columns(cols ...field.Expr) gen.Columns { return u.userAddressDo.Columns(cols...) }

func (u *userAddress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userAddress) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 15)
	u.fieldMap["address_id"] = u.AddressID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["address_type"] = u.AddressType
	u.fieldMap["is_default"] = u.IsDefault
	u.fieldMap["recipient_name"] = u.RecipientName
	u.fieldMap["address_line1"] = u.AddressLine1
	u.fieldMap["address_line2"] = u.AddressLine2
	u.fieldMap["city"] = u.City
	u.fieldMap["state_province"] = u.StateProvince
	u.fieldMap["postal_code"] = u.PostalCode
	u.fieldMap["country_code"] = u.CountryCode
	u.fieldMap["phone"] = u.Phone
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u userAddress) clone(db *gorm.DB) userAddress {
	u.userAddressDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userAddress) replaceDB(db *gorm.DB) userAddress {
	u.userAddressDo.ReplaceDB(db)
	return u
}

type userAddressDo struct{ gen.DO }

func (u userAddressDo) Debug() *userAddressDo {
	return u.withDO(u.DO.Debug())
}

func (u userAddressDo) WithContext(ctx context.Context) *userAddressDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userAddressDo) ReadDB() *userAddressDo {
	return u.Clauses(dbresolver.Read)
}

func (u userAddressDo) WriteDB() *userAddressDo {
	return u.Clauses(dbresolver.Write)
}

func (u userAddressDo) Session(config *gorm.Session) *userAddressDo {
	return u.withDO(u.DO.Session(config))
}

func (u userAddressDo) Clauses(conds ...clause.Expression) *userAddressDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userAddressDo) Returning(value interface{}, columns ...string) *userAddressDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userAddressDo) Not(conds ...gen.Condition) *userAddressDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userAddressDo) Or(conds ...gen.Condition) *userAddressDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userAddressDo) Select(conds ...field.Expr) *userAddressDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userAddressDo) Where(conds ...gen.Condition) *userAddressDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userAddressDo) Order(conds ...field.Expr) *userAddressDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userAddressDo) Distinct(cols ...field.Expr) *userAddressDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userAddressDo) Omit(cols ...field.Expr) *userAddressDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userAddressDo) Join(table schema.Tabler, on ...field.Expr) *userAddressDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userAddressDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userAddressDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userAddressDo) RightJoin(table schema.Tabler, on ...field.Expr) *userAddressDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userAddressDo) Group(cols ...field.Expr) *userAddressDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userAddressDo) Having(conds ...gen.Condition) *userAddressDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userAddressDo) Limit(limit int) *userAddressDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userAddressDo) Offset(offset int) *userAddressDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userAddressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userAddressDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userAddressDo) Unscoped() *userAddressDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userAddressDo) Create(values ...*model.UserAddress) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userAddressDo) CreateInBatches(values []*model.UserAddress, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userAddressDo) Save(values ...*model.UserAddress) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userAddressDo) First() (*model.UserAddress, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAddress), nil
	}
}

func (u userAddressDo) Take() (*model.UserAddress, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAddress), nil
	}
}

func (u userAddressDo) Last() (*model.UserAddress, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAddress), nil
	}
}

func (u userAddressDo) Find() ([]*model.UserAddress, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserAddress), err
}

func (u userAddressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserAddress, err error) {
	buf := make([]*model.UserAddress, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userAddressDo) FindInBatches(result *[]*model.UserAddress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userAddressDo) Attrs(attrs ...field.AssignExpr) *userAddressDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userAddressDo) Assign(attrs ...field.AssignExpr) *userAddressDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userAddressDo) Joins(fields ...field.RelationField) *userAddressDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userAddressDo) Preload(fields ...field.RelationField) *userAddressDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userAddressDo) FirstOrInit() (*model.UserAddress, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAddress), nil
	}
}

func (u userAddressDo) FirstOrCreate() (*model.UserAddress, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAddress), nil
	}
}

func (u userAddressDo) FindByPage(offset int, limit int) (result []*model.UserAddress, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userAddressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userAddressDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userAddressDo) Delete(models ...*model.UserAddress) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userAddressDo) withDO(do gen.Dao) *userAddressDo {
	u.DO = *do.(*gen.DO)
	return u
}
