// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBid = "bids"

// Bid mapped from table <bids>
type Bid struct {
	BidID        string    `gorm:"column:bid_id;primaryKey" json:"bid_id"`
	AuctionID    string    `gorm:"column:auction_id;not null" json:"auction_id"`
	BidderID     string    `gorm:"column:bidder_id;not null" json:"bidder_id"`
	BidAmount    float64   `gorm:"column:bid_amount;not null" json:"bid_amount"`
	MaxBidAmount float64   `gorm:"column:max_bid_amount" json:"max_bid_amount"`
	BidStatus    string    `gorm:"column:bid_status;not null;default:active" json:"bid_status"`
	IPAddress    string    `gorm:"column:ip_address" json:"ip_address"`
	UserAgent    string    `gorm:"column:user_agent" json:"user_agent"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Bid's table name
func (*Bid) TableName() string {
	return TableNameBid
}
