// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCartItem = "cart_items"

// CartItem mapped from table <cart_items>
type CartItem struct {
	CartItemID    int32     `gorm:"column:cart_item_id;primaryKey;autoIncrement:true" json:"cart_item_id"`
	CartID        string    `gorm:"column:cart_id;not null" json:"cart_id"`
	ProductID     string    `gorm:"column:product_id;not null" json:"product_id"`
	VariantID     int32     `gorm:"column:variant_id" json:"variant_id"`
	Quantity      int32     `gorm:"column:quantity;not null" json:"quantity"`
	PriceSnapshot float64   `gorm:"column:price_snapshot;not null" json:"price_snapshot"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName CartItem's table name
func (*CartItem) TableName() string {
	return TableNameCartItem
}
