// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	OrderID           string         `gorm:"column:order_id;primaryKey" json:"order_id"`
	UserID            string         `gorm:"column:user_id;not null" json:"user_id"`
	OrderNumber       string         `gorm:"column:order_number;not null" json:"order_number"`
	OrderType         string         `gorm:"column:order_type;not null" json:"order_type"`
	AuctionID         string         `gorm:"column:auction_id" json:"auction_id"`
	Subtotal          float64        `gorm:"column:subtotal;not null" json:"subtotal"`
	TaxAmount         float64        `gorm:"column:tax_amount;not null" json:"tax_amount"`
	ShippingAmount    float64        `gorm:"column:shipping_amount;not null" json:"shipping_amount"`
	DiscountAmount    float64        `gorm:"column:discount_amount;not null" json:"discount_amount"`
	TotalAmount       float64        `gorm:"column:total_amount;not null" json:"total_amount"`
	OrderStatus       string         `gorm:"column:order_status;not null;default:pending" json:"order_status"`
	BillingAddressID  int32          `gorm:"column:billing_address_id" json:"billing_address_id"`
	ShippingAddressID int32          `gorm:"column:shipping_address_id" json:"shipping_address_id"`
	CustomerNotes     string         `gorm:"column:customer_notes" json:"customer_notes"`
	AdminNotes        string         `gorm:"column:admin_notes" json:"admin_notes"`
	IPAddress         string         `gorm:"column:ip_address" json:"ip_address"`
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
