// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductTag = "product_tags"

// ProductTag mapped from table <product_tags>
type ProductTag struct {
	ProductID string    `gorm:"column:product_id;primaryKey" json:"product_id"`
	TagID     int32     `gorm:"column:tag_id;primaryKey" json:"tag_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName ProductTag's table name
func (*ProductTag) TableName() string {
	return TableNameProductTag
}
