// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameShipmentTrackingHistory = "shipment_tracking_history"

// ShipmentTrackingHistory mapped from table <shipment_tracking_history>
type ShipmentTrackingHistory struct {
	TrackingHistoryID int32     `gorm:"column:tracking_history_id;primaryKey;autoIncrement:true" json:"tracking_history_id"`
	ShipmentID        int32     `gorm:"column:shipment_id;not null" json:"shipment_id"`
	Status            string    `gorm:"column:status;not null" json:"status"`
	Location          string    `gorm:"column:location" json:"location"`
	Description       string    `gorm:"column:description" json:"description"`
	TrackedAt         time.Time `gorm:"column:tracked_at;not null;default:CURRENT_TIMESTAMP" json:"tracked_at"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName ShipmentTrackingHistory's table name
func (*ShipmentTrackingHistory) TableName() string {
	return TableNameShipmentTrackingHistory
}
